/**
 * Secure Audio Service
 *
 * Provides secure audio streaming for family users via time-limited signed URLs.
 * Uses Supabase Storage signed URLs with 1-hour expiry.
 *
 * Story 4.2: Secure Streaming Player (AC: 1, 4)
 */

import { supabase } from '@/lib/supabase';
import { devLog } from '@/lib/devLogger';

/** Signed URL expiry time in seconds (1 hour) */
const SIGNED_URL_EXPIRY_SECONDS = 3600;
const AUDIO_STORAGE_BUCKET = 'audio-recordings';

/** Refresh threshold - refresh URL when less than 5 minutes remaining */
const REFRESH_THRESHOLD_SECONDS = 300;

/**
 * Represents a signed audio URL with expiry information.
 */
export interface SignedAudioUrl {
  /** The signed URL for audio streaming */
  url: string;
  /** Unix timestamp (ms) when the URL expires */
  expiresAt: number;
}

/**
 * Storage path info from audio_recordings table.
 */
interface StoragePathResult {
  id: string;
  file_path: string;
  sync_status: string;
}

/**
 * Generates a time-limited signed URL for secure audio streaming.
 *
 * The URL is valid for 1 hour and can only be generated by authenticated
 * users who have access to the story via RLS policies.
 *
 * @param storyId - The story UUID to generate URL for
 * @returns SignedAudioUrl with URL and expiry timestamp
 * @throws Error if story not found, not synced, or URL generation fails
 */
export async function getSignedAudioUrl(storyId: string): Promise<SignedAudioUrl> {
  // First, get the storage path from audio_recordings
  const { data: story, error: storyError } = await supabase
    .from('audio_recordings')
    .select('id, file_path, sync_status')
    .eq('id', storyId)
    .eq('sync_status', 'synced')
    .single();

  if (storyError) {
    devLog.error('[secureAudioService] Failed to fetch story:', storyError.message);
    throw new Error(`Story not found: ${storyError.message}`);
  }

  if (!story) {
    throw new Error('Story not found or not accessible');
  }

  const storyData = story as StoragePathResult;

  // Extract storage path from file_path
  // file_path format: local path or storage path
  // For cloud storage, we need to derive the storage path
  const storagePath = deriveStoragePath(storyData.file_path, storyId);

  // Generate signed URL from Supabase Storage
  const { data, error } = await supabase.storage
    .from(AUDIO_STORAGE_BUCKET)
    .createSignedUrl(storagePath, SIGNED_URL_EXPIRY_SECONDS);

  if (error) {
    devLog.error('[secureAudioService] Failed to generate signed URL:', error.message);
    throw new Error(`Failed to generate signed URL: ${error.message}`);
  }

  if (!data?.signedUrl) {
    throw new Error('No signed URL returned from storage');
  }

  return {
    url: data.signedUrl,
    expiresAt: Date.now() + SIGNED_URL_EXPIRY_SECONDS * 1000,
  };
}

/**
 * Derives the storage path from the local file path.
 *
 * Storage path format: {user_id}/{recording_id}.wav
 * Local file path format: file:///path/to/recordings/{recording_id}.wav
 *
 * @param filePath - The local file path
 * @param storyId - The story UUID
 * @returns The storage path for Supabase Storage
 */
function deriveStoragePath(filePath: string, storyId: string): string {
  const normalized = filePath.trim();
  if (!normalized) {
    return `${storyId}.wav`;
  }

  // Local app path (file://...) - cloud object naming is {storyId}.{ext}
  if (normalized.startsWith('file://')) {
    return `${storyId}${extractAudioExtension(normalized)}`;
  }

  // Already a plain storage object path
  if (/^[^/]+\.(wav|opus)$/i.test(normalized)) {
    return normalized;
  }

  // Current canonical cloud path: {userId}/{recordingId}.{ext}
  if (/^[^/]+\/[^/]+\.(wav|opus)$/i.test(normalized)) {
    return normalized;
  }

  // Backward compatibility for legacy "recordings/<file>" storage paths.
  if (normalized.startsWith('recordings/')) {
    return normalized.replace(/^recordings\//, '');
  }

  if (/\.(wav|opus)$/i.test(normalized)) {
    return normalized;
  }

  return `${storyId}${extractAudioExtension(normalized)}`;
}

function extractAudioExtension(path: string): '.wav' | '.opus' {
  return path.toLowerCase().endsWith('.opus') ? '.opus' : '.wav';
}

/**
 * Checks if a signed URL should be refreshed.
 *
 * Returns true if less than 5 minutes remaining before expiry.
 *
 * @param expiresAt - Unix timestamp (ms) when URL expires
 * @returns true if URL should be refreshed
 */
export function shouldRefreshUrl(expiresAt: number): boolean {
  const remainingMs = expiresAt - Date.now();
  return remainingMs < REFRESH_THRESHOLD_SECONDS * 1000;
}

/**
 * Checks if a signed URL has expired.
 *
 * @param expiresAt - Unix timestamp (ms) when URL expires
 * @returns true if URL has expired
 */
export function isUrlExpired(expiresAt: number): boolean {
  return Date.now() >= expiresAt;
}
