param(
    [string]$ProjectId = $env:SUPABASE_PROJECT_ID,
    [string]$Schema = "public",
    [string]$MobileOutput = "src/types/supabase.generated.ts",
    [string]$WebOutput = "..\TimeLog-Web\src\types\supabase.generated.ts"
)

$ErrorActionPreference = "Stop"

if (-not $ProjectId) {
    throw "Missing SUPABASE_PROJECT_ID. Set the environment variable or pass -ProjectId."
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$mobileTarget = Join-Path $repoRoot $MobileOutput

$webOutputCandidates = @(
    $WebOutput,
    "..\timelog-web\src\types\supabase.generated.ts"
) | Select-Object -Unique

$webTarget = $null
foreach ($candidate in $webOutputCandidates) {
    $candidateTarget = Join-Path $repoRoot $candidate
    $candidateRoot = Split-Path $candidateTarget
    $candidateProjectRoot = Split-Path (Split-Path $candidateRoot)
    if (Test-Path $candidateProjectRoot) {
        $webTarget = $candidateTarget
        break
    }
}

$header = @(
    "// Generated by scripts/generate-supabase-types.ps1"
    "// Do not edit this file manually."
    ""
) -join [Environment]::NewLine

$supabaseCli = Get-Command "supabase" -ErrorAction SilentlyContinue
if ($supabaseCli) {
    $generatedLines = & supabase gen types typescript --project-id $ProjectId --schema $Schema
} else {
    $generatedLines = & npx supabase gen types typescript --project-id $ProjectId --schema $Schema
}
if ($LASTEXITCODE -ne 0) {
    throw "supabase gen types failed with exit code $LASTEXITCODE."
}

$generated = if ($generatedLines -is [System.Array]) {
    $generatedLines -join [Environment]::NewLine
} else {
    [string]$generatedLines
}
$content = $header + [Environment]::NewLine + $generated + [Environment]::NewLine

New-Item -ItemType Directory -Force -Path (Split-Path $mobileTarget) | Out-Null
Set-Content -Path $mobileTarget -Value $content -Encoding UTF8
Write-Host "Updated mobile types: $mobileTarget"

$webRoot = if ($webTarget) { Split-Path $webTarget } else { $null }
if ($webRoot -and (Test-Path (Split-Path (Split-Path $webRoot)))) {
    New-Item -ItemType Directory -Force -Path $webRoot | Out-Null
    Set-Content -Path $webTarget -Value $content -Encoding UTF8
    Write-Host "Updated web types: $webTarget"
} else {
    $targets = ($webOutputCandidates | ForEach-Object { Join-Path $repoRoot $_ }) -join "; "
    Write-Warning "Web target directory not found. Checked: $targets"
}
